<?php

/**
 * Implements hook_node_info().
 */
function hosting_scheduled_task_node_info() {
  $types["scheduled_task"] = array(
    "type" => 'scheduled_task',
    "name" => t('Scheduled Task'),
    'base' => 'hosting_scheduled_task',
    "has_title" => FALSE,
    "title_label" => '',
//    "description" => hosting_node_help("task"),
    "has_body" => 0,
    "body_label" => '',
    "min_word_count" => 0,
  );

  return $types;
}

/**
 * Implements hook_node_access().
 */
function hosting_scheduled_task_node_access($node, $op, $account) {
  $type = is_string($node) ? $node : $node->type;

  if ($type == 'scheduled_task') {
    if (user_access('administer scheduled tasks', $account)) {
      return NODE_ACCESS_ALLOW;
    }
  }
}

/**
 * Implements hook_permission().
 */
function hosting_scheduled_task_permission() {
  return array(
    'administer scheduled tasks' => array(
      'title' => t('Administer scheduled tasks'),
    ),
  );
}

function hosting_scheduled_task_task_type_options() {
  $options = array();
  foreach (hosting_available_tasks() as $target_type => $tasks) {
    foreach ($tasks as $task_type => $task) {
      $options[$target_type . '__' . $task_type] = t('!target_name - !task_name', array('!target_name' => node_type_get_name($target_type), '!task_name' => $task['title']));
    }
  }
  return $options;
}

/**
 * Implements hook_form().
 */
function hosting_scheduled_task_form(&$node) {
  $form = array();

  return $form;
}
